### PR TITLE
fix: Improves CLI operations for `ephemeral` and `sequential` params

### PR DESCRIPTION
**Pull request by afzal442**
For #20 

e.g.
```
[fk: 2023-04-03 19:47:24.456485 aws:faaskeeper-dev(CONNECTED) session:2ee45722 2] create /test 0x0 -e
['/test', '0x0', 'True', 'False']
```

cc @mcopik

### CODE REVIEW

**Comment by mcopik** [comment]
@afzal442 Thanks! The implementation seems pretty fixed for the arguments of the `create` operation, and it will be difficult to maintain and expand. After all, there are many more commands that we would like to support.

I think the alternative approach posted by @shailendrasingh117 will be more modular. Maybe you can both collaborate on a single solution?

**Comment by afzal442** [comment]
Thanks @mcopik! we can support for `create` operation by adding condition ```if cmd == `create` ``` simply now. 

Talking about the alternative approach, I had that same thing figured out but I don't know the use cases of get_data and set_data. That idea support for cmd is limited. What if cmd is sth else like `connect` ``` if command not in COMMANDS:
       click.echo(f"Invalid command: {command}") ```. I'm not sure what it does and how it calls unkown methods.
``` if command == "create":
       create_node(**kwargs)
   elif command == "get_data":
       get_data(**kwargs)
   elif command == "set_data":
       set_data(**kwargs)
```
LMK what you think.

**Review by shailendrasingh117 — APPROVED** [review]

**Comment by shailendrasingh117** [comment]
This approach can also make it difficult to handle errors in a consistent way. If an unknown command is passed to the dispatcher, the current implementation simply prints an error message to the console. However, in a more complex application, it might be more appropriate to raise an exception or return an error code to the caller.
@mcopik @afzal442

**Comment by afzal442** [comment]
Closed as no progress

**Pull request closed without merging**
