### PR TITLE
Add support for Indirect output communication

### PR DESCRIPTION
**Pull request by ziadhany**
issue: #15

### CODE REVIEW

**Comment by ziadhany** [comment]
@mcopik what do you think should be sent to the queue instead of the socket ( address, IP )? 
and should all functions use `config.client_channel.notify` ?

**Comment by mcopik** [comment]
@ziadhany Thanks for the contribution! I was planning to work on this well since we need this feature ASAP.

This needs testing, but I would be happy to merge it into my PR #29 to a working branch before we merge it together to master. Can you please resolve issues described above? I think we can leave watch and heartbeat at the moment intact.

>  what do you think should be sent to the queue instead of the socket ( address, IP )?

Client ID, nothing else. In future, we will use that to handle multiple queues.

> and should all functions use config.client_channel.notify ?

That would be the ultimate goal.

**Comment by ziadhany** [comment]
> This needs testing, but I would be happy to merge it into my PR #29 to a working branch before we merge it together to master.

ok, I will add some tests

> Can you please resolve issues described above? I think we can leave watch and heartbeat at the moment intact.

sure, I will do my best to solve this issue 😀

**Comment by mcopik** [comment]
Hi @ziadhany! Thanks again for your help - I had to push the work on SQS since we need it for the release. I cherry-picked your SQS commits into the main branch and wrapped up the work merged in #29.

Thanks again for your help!

**Comment by ziadhany** [comment]
> Hi @ziadhany! Thanks again for your help - I had to push the work on SQS since we need it for the release. I cherry-picked your SQS commits into the main branch and wrapped up the work merged in #29.
> 
> Thanks again for your help!

@mcopik You are welcome! , I'm always happy to help out

**Pull request closed without merging**
